import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedcamerawidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/newapp/generatedcamerawidget/generated/GeneratedImage5Widget1.dart';

/* Frame camera
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCameraWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFlashWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 390.0,
          height: 844.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 0, 0, 0),
                  ),
                ),
                Positioned(
                  left: -1.0,
                  top: 63.0,
                  right: null,
                  bottom: null,
                  width: 391.0,
                  height: 632.0,
                  child: GeneratedImage5Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 390.0,
                  height: 844.0,
                  child: GeneratedFrame1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
