import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedadwidget/generated/GeneratedGroupWidget266.dart';
import 'package:flutterapp/newapp/generatedadwidget/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedadwidget/generated/GeneratedClosecircleWidget.dart';

/* Frame Ad
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedAdWidget1'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 390.0,
          height: 844.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              // overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.040860608907846305;

                    final double height =
                        constraints.maxHeight * 0.00971937744538366;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.24600016276041667,
                          y: constraints.maxHeight * 0.9459978438101674,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget266(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth;

                    final double height = constraints.maxHeight;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: 0,
                          y: 0,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedImage4Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.1282051282051282;

                    final double height =
                        constraints.maxHeight * 0.05924170616113744;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.8256410256410256,
                          y: constraints.maxHeight * 0.06635071090047394,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedClosecircleWidget(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
