import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedVectorWidget299.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedIandooleyd1UPkiFd04Aunsplash1Widget1.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroup77Widget1.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedRectangle17687Widget8.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedtrendyWidget1.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroup106Widget.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroupWidget213.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroupWidget262.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedEventsWidget2.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroupWidget253.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedVectorWidget247.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroup107Widget5.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroup91Widget2.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedOrignalsoundbyjohnWidget1.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedGroupWidget243.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedEllipse307Widget7.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/Generated0Widget4.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/Generated3Widget1.dart';
import 'package:flutterapp/newapp/generatedswipewidget/generated/GeneratedpuppyloveWidget1.dart';

/* Frame Swipe
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSwipeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -23.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 552.0,
                height: 845.0,
                child: GeneratedImage3Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.040860608907846305;

                  final double height =
                      constraints.maxHeight * 0.00971937744538366;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24600016276041667,
                        y: constraints.maxHeight * 0.9459978438101674,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget213(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1724076686761318;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 67.2389907836914;

                  double percentHeight = 0.07966705069157749;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      67.2389907836914;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.023076923076923078,
                        translateY: constraints.maxHeight * 0.8116113744075829,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget247())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 105.0,
                child: GeneratedGroup106Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 63.0,
                child: GeneratedGroup91Widget2(),
              ),
              Positioned(
                left: 333.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse307Widget7(),
              ),
              Positioned(
                left: 333.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedIandooleyd1UPkiFd04Aunsplash1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10915165436573518;

                  final double height =
                      constraints.maxHeight * 0.04772081872298254;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8384615384615385,
                        y: constraints.maxHeight * 0.4905306558473415,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget243(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.09581050383738983;

                  final double height =
                      constraints.maxHeight * 0.0424536393152029;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8494247045272436,
                        y: constraints.maxHeight * 0.5749617662475007,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget253(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 346.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 5.0,
                child: Generated3Widget1(),
              ),
              Positioned(
                left: 346.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 5.0,
                child: Generated0Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0867188478127504;

                  final double height =
                      constraints.maxHeight * 0.03588321423643573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8585605719150641,
                        y: constraints.maxHeight * 0.6585485087751777,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget262(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07435897435897436;
                  double scaleX = (constraints.maxWidth * percentWidth) / 29.0;

                  double percentHeight = 0.035545023696682464;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8666666666666667,
                        translateY: constraints.maxHeight * 0.7417061611374408,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget299())
                  ]);
                }),
              ),
              Positioned(
                left: 331.275634765625,
                top: 681.9448852539062,
                right: null,
                bottom: null,
                width: 37.055118560791016,
                height: 37.055118560791016,
                child: GeneratedGroup77Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 28.0,
                child: GeneratedRectangle17687Widget8(),
              ),
              Positioned(
                left: 26.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 5.0,
                child: GeneratedEventsWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 5.0,
                child: GeneratedpuppyloveWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 691.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 5.0,
                child: GeneratedtrendyWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 2.0,
                child: GeneratedOrignalsoundbyjohnWidget1(),
              ),
              Positioned(
                left: 168.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 54.0,
                child: GeneratedGroup107Widget5(),
              )
            ]),
      ),
    ));
  }
}
