import 'package:flutter/material.dart';
import 'package:flutterapp/screens/splash_screen.dart';
import 'package:flutterapp/newapp/generatedsplashscreenwidget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/newapp/generatedsplashscreenwidget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/newapp/generatedsplashscreenwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedsplashscreenwidget/generated/GeneratedGroup49Widget.dart';
import 'package:get/get.dart';

/* Frame Splashscreen
    Autogenerated by FlutLab FTF Generator
  */
class Splash extends StatelessWidget {
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
      width: Get.width,
      height: Get.height,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          top: 0.0,
          right: null,
          bottom: null,
          width: Get.width,
          height: Get.height,
          child: SplashScreen(),
        ),
        Positioned(
          left: 129.0,
          top: 513.0,
          right: null,
          bottom: null,
          width: 156.59182739257812,
          height: 166.40240478515625,
          child: GeneratedGroup1Widget(),
        ),
        Positioned(
          left: Get.width * 0.07,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.5615384615384615;

            final double height = constraints.maxHeight * 0.21800947867298578;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.2076923076923077,
                  y: constraints.maxHeight * 0.08886255924170616,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedGroup49Widget(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: Get.width * 0.2,
          top: Get.height * 0.4,
          right: null,
          bottom: null,
          width: Get.width * 0.8,
          height: Get.height * 0.3,
          child: GeneratedGroup48Widget(),
        ),
        //Get Started Botton
        Positioned(
          left: Get.width * 0.08,
          bottom: Get.height * 0.1,
          width: Get.width * 0.9,
          height: Get.height * 0.1,
          child: GeneratedGroup52Widget(),
        )
      ]),
    ));
  }
}
