import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedVectorWidget78.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedKeyboardbackspaceWidget1.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedWoofbyYumwoof41Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedGroup81Widget2.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedRectangle17700Widget1.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedYumwoofsocialWidget1.dart';
import 'package:flutterapp/newapp/generatedprofilewidget2/generated/GeneratedGroupWidget65.dart';
import 'package:get/get.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
        width: Get.width,
        height: Get.height,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 230, 211),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.040860608907846305;

                  final double height =
                      constraints.maxHeight * 0.00971937744538366;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24600016276041667,
                        y: constraints.maxHeight * 0.9459978438101674,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget65(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.16587677725118483;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle17700Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6666666666666666;

                  final double height =
                      constraints.maxHeight * 0.045023696682464455;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16666666666666666,
                        y: constraints.maxHeight * 0.11492890995260663,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup81Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06153846153846154;

                  final double height =
                      constraints.maxHeight * 0.02843601895734597;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05897435897435897,
                        y: constraints.maxHeight * 0.058056872037914695,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboardbackspaceWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.24871794871794872;

                  final double height =
                      constraints.maxHeight * 0.018957345971563982;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.45897435897435895,
                        y: constraints.maxHeight * 0.9360189573459715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedYumwoofsocialWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.2564102564102564;
                  double scaleX = (constraints.maxWidth * percentWidth) / 100.0;

                  double percentHeight = 0.10545023696682465;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 89.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.34615384615384615,
                        translateY: constraints.maxHeight * 0.8471563981042654,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget78())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.6042654028436019;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.18246445497630331,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWoofbyYumwoof41Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
