import 'package:flutter/material.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget316 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 0.6453731060028076,
      height: 0.1235802099108696,
    ));
  }
}
