import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Text Friends
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFriendsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.01,
        c: 0.01,
        d: 1.00,
        child: Text(
          '''Friends''',
          overflow: TextOverflow.visible,
          textAlign: TextAlign.left,
          style: TextStyle(
            height: 0.0,
            fontSize: 22.0,
            fontFamily: 'Poppins',
            fontWeight: FontWeight.w400,
            color: Color.fromARGB(255, 255, 255, 255),

            /* letterSpacing: 0.0, */
          ),
        ));
  }
}
