import 'package:flutter/material.dart';

/* Text #trendy
    Autogenerated by FlutLab FTF Generator
  */
class TrendyHashTagWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''#trendy''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 0.0,
        fontSize: 17.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
