import 'package:flutter/material.dart';

import '../../helpers/svg/svg.dart';
import '../../helpers/transform/transform.dart';
import '../../newapp/generateddiscoverwidget2/generated/GeneratedVectorWidget147.dart';

/* Group Group 102
    Autogenerated by FlutLab FTF Generator
  */
class SearchWidget extends StatelessWidget {
  double width;
  double height;
  SearchWidget({required this.height, required this.width});
  @override
  Widget build(BuildContext context) {
    return Container(
      width: width,
      height: height,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Container(
          color: Color.fromARGB(255, 243, 230, 211),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              SizedBox(
                width: width*0.83,
                height: height,
                child: Padding(
                  padding: const EdgeInsets.only(left: 2.0),
                  child: TextField(
                    decoration: InputDecoration(
                      border: InputBorder.none,
                      hintText: 'Woof here...',
                      hintStyle: TextStyle(
                      height: 1.5,
                      fontSize: 13.0,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 168, 168, 68),
                    ),
                    ),
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.5,
                      fontSize: 13.0,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 168, 168, 68),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
              ),
              Stack(
                children: [
                  Container(
                    width: 40.0,
                    height: 40.0,
                    child: SvgWidget(painters: [
                      SvgPathPainter.fill()
                        ..addPath(
                            'M40 20C40 31.0457 31.0457 40 20 40C8.9543 40 0 31.0457 0 20C0 8.9543 8.9543 0 20 0C31.0457 0 40 8.9543 40 20Z')
                        ..color = Color.fromARGB(255, 38, 44, 10),
                    ]),
                  ),
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Padding(
                      padding: const EdgeInsets.only(left: 8.0),
                      child: Center(
                        child: Container(
                          width: 24.0,
                          height: 24.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              // overflow: Overflow.visible,
                              children: [
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: 0.0,
                                  bottom: 0.0,
                                  width: null,
                                  height: null,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    double percentWidth = 0.7291666666666666;
                                    double scaleX =
                                        (constraints.maxWidth * percentWidth) /
                                            17.5;

                                    double percentHeight = 0.7291666666666666;
                                    double scaleY =
                                        (constraints.maxHeight * percentHeight) /
                                            17.5;

                                    return Stack(children: [
                                      TransformHelper.translateAndScale(
                                          translateX: constraints.maxWidth * 0.125,
                                          translateY: constraints.maxHeight * 0.125,
                                          translateZ: 0,
                                          scaleX: scaleX,
                                          scaleY: scaleY,
                                          scaleZ: 1,
                                          child: GeneratedVectorWidget147())
                                    ]);
                                  }),
                                )
                              ]),
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
