import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/Generated1234Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/Generated1234friendsWidget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedMattyAdamsWidget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedEllipse307Widget3.dart';

/* Group Group 116
    Autogenerated by FlutLab FTF Generator
  */
class TrendingProfile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    double screenHeight = MediaQuery.of(context).size.height;
    double screenWidth = MediaQuery.of(context).size.width;
    return Container(
      width: 200.0,
      height: 85.0,
      child: Stack(fit: StackFit.expand, alignment: Alignment.center,
          // overflow: Overflow.visible,
          children: [
            Positioned(
              left: 83.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 165.0,
              height: 11.0,
              child: GeneratedMattyAdamsWidget(
                name: 'Matty Adams',
              ),
            ),
            Positioned(
              left: 83.0,
              top: 37.0,
              right: null,
              bottom: null,
              width: 86.0,
              height: 14.0,
              child: Generated1234Widget(
                username: '1234',
              ),
            ),
            Positioned(
              left: 83.0,
              top: 49.0,
              right: null,
              bottom: null,
              width: 83.0,
              height: 12.0,
              child: Generated1234friendsWidget(friends: '1234'),
            ),
            // Positioned(
            //   left: 0.0,
            //   top: 0.0,
            //   right: null,
            //   bottom: null,
            //   width: 74.0,
            //   height: 74.0,
            //   child: GeneratedEllipse307Widget3(),
            // ),
            Positioned(
                left: 0,
                top: 0,
                right: null,
                bottom: null,
                child: CircleAvatar(
                  radius: MediaQuery.of(context).size.width * 0.1,
                  backgroundColor:Color.fromARGB(255, 168, 168, 68),
                  child: CircleAvatar(
                    radius: MediaQuery.of(context).size.width * 0.09,
                    backgroundImage: AssetImage(
                        'assets/images/4f22cf0939ef951a05a74e0fe790259a335322dc.png'),
                  ),
                ))
          ]),
    );
  }
}
