import 'package:flutter/material.dart';

/* Rectangle Rectangle 17689
    Autogenerated by FlutLab FTF Generator
  */
class CamScreen extends StatelessWidget {
  var callBackFunction;
  CamScreen({required this.callBackFunction});
  @override
  Widget build(BuildContext context) {
    return callBackFunction()(
      child: Container(
        width: 152.0,
        height: 48.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(26.0),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(26.0),
          child: Container(
            color: Color.fromARGB(255, 64, 64, 64),
          ),
        ),
      ),
    );
  }
}
