import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedcam2widget/generated/GeneratedGroupWidget212.dart';
import 'package:flutterapp/newapp/generatedcam2widget/generated/GeneratedGroup100Widget1.dart';
import 'package:flutterapp/newapp/generatedcam2widget/generated/GeneratedImage5Widget2.dart';
import 'package:flutterapp/newapp/generatedcam2widget/generated/GeneratedWindowcloseWidget1.dart';
import 'package:flutterapp/newapp/generatedcam2widget/generated/GeneratedGroup99Widget.dart';
import 'package:get/get.dart';

/* Frame cam2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCam2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
        width: Get.width,
        height: Get.height,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 0, 0, 0),
                ),
              ),
              Positioned(
                top: Get.height*0.1,
                child: GeneratedImage5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.040860608907846305;

                  final double height =
                      constraints.maxHeight * 0.00971937744538366;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24600016276041667,
                        y: constraints.maxHeight * 0.9459978438101674,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget212(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                right: 10.0,
                top: 30.0,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedWindowcloseWidget1(),
              ),
              Positioned(
                left: 30.0,
                bottom: Get.height*0.1,
                child: GeneratedGroup99Widget(),
              ),
              Positioned(
                right: 30,
                bottom: Get.height*0.1,
                child: GeneratedGroup100Widget1(),
              )
            ]),
      ),
    );
  }
}
