import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup89Widget3.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup101Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage14Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedRectangle17687Widget5.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup107Widget3.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup102Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage13Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedVectorWidget149.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroupWidget127.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage8Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage12Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup93Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup88Widget3.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup91Widget1.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup87Widget3.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup92Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedGroup90Widget3.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedRectangle17686Widget2.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget4/generated/GeneratedImage9Widget.dart';
import 'package:get/get.dart';

/* Frame Discover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscoverWidget4 extends StatefulWidget {
  @override
  State<GeneratedDiscoverWidget4> createState() =>
      _GeneratedDiscoverWidget4State();
}

class _GeneratedDiscoverWidget4State extends State<GeneratedDiscoverWidget4> {
  bool isSelected = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: Get.width,
        height: Get.height,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 230, 211),
                ),
              ),
              Positioned(
                left: 9.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: Get.width * 0.95,
                height: Get.height * 0.2,
                child: GeneratedImage14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                width: Get.width,
                height: Get.height * 0.2,
                child: GeneratedRectangle17686Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.040860608907846305;

                  final double height =
                      constraints.maxHeight * 0.00971937744538366;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24600016276041667,
                        y: constraints.maxHeight * 0.9459978438101674,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget127(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1724076686761318;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 67.2389907836914;

                  double percentHeight = 0.07966705069157749;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      67.2389907836914;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.023076923076923078,
                        translateY: constraints.maxHeight * 0.8116113744075829,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget149())
                  ]);
                }),
              ),
              //
              Positioned(
                left: 19.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 67.09091186523438,
                height: 27.0,
                child: GeneratedGroup8Widget1(),
              ),
              Positioned(
                left: 112.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 67.09091186523438,
                height: 27.0,
                child: GeneratedGroup91Widget1(),
              ),
              Positioned(
                left: 202.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 67.09091186523438,
                height: 27.0,
                child: GeneratedGroup92Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 67.09091186523438,
                height: 27.0,
                child: GeneratedGroup93Widget(),
              ),

              Positioned(
                left: 9.0,
                top: Get.height * 0.2,
                width: Get.width * 0.95,
                height: Get.height * 0.1,
                child: GeneratedImage14Widget(),
              ),
              Positioned(
                left: 9.0,
                top: Get.height * 0.32,
                width: Get.width * 0.95,
                height: Get.height * 0.15,
                child: GeneratedImage14Widget(),
              ),
              Positioned(
                left: 9.0,
                top: Get.height * 0.5,
                width: Get.width * 0.95,
                height: Get.height * 0.1,
                child: GeneratedImage14Widget(),
              ),

              isSelected ? Positioned(
                left: Get.width * 0.06,
                top: 75.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 535.0,
                child: GeneratedGroup101Widget(),
              ): Container(),
              Positioned(
                  left: Get.width * 0.06,
                  top: Get.height * 0.05,
                  right: null,
                  bottom: null,
                  width: 351.8376159667969,
                  height: 46.435420989990234,
                  child: GestureDetector(
                    onTap: () {
                  if (isSelected == false) {
                    setState(() {
                      isSelected = true;
                    });
                  }
                },
                    child: GeneratedGroup102Widget()),
                ),
              
            ]),
      ),
    );
  }
}
