import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedKeyboardbackspaceWidget2.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedRewardsWidget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedYummywolfSocialWidget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedYummywolfhelpsyouwarnRewardsWidget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedGroupWidget66.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedGroup105Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedRectangle17691Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/Generated2098Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedEarnRewardsWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/Generated\$89Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedBalnceWidget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget3/generated/GeneratedTotalTokensWidget.dart';
import 'package:get/get.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
        width: Get.width,
        height: Get.height,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 230, 211),
                ),
              ),
              Positioned(
                left: Get.width*0.07,
                top: Get.height*0.12,
                width: Get.width,
                height: 28.0,
                child: GeneratedYummywolfSocialWidget(),
              ),
              Positioned(
                left: Get.width*0.07,
                top: Get.height*0.18,
                width: Get.width,
                height: 31.0,
                child: GeneratedRewardsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.040860608907846305;

                  final double height =
                      constraints.maxHeight * 0.00971937744538366;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24600016276041667,
                        y: constraints.maxHeight * 0.9459978438101674,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget66(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: Get.width*0.4,
                top: Get.height * 0.65,
                width: Get.width,
                height: 2.0,
                child: GeneratedEarnRewardsWidget(),
              ),
              Positioned(
                left: Get.width*0.2,
                top: Get.height * 0.73,
                width: Get.width,
                height: 2.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedYummywolfhelpsyouwarnRewardsWidget()),
              ),
              Positioned(
                left: Get.width*0.07,
                top: Get.height*0.25,
                width: Get.width*0.85,
                height: Get.height*0.2,
                child: GeneratedRectangle17691Widget(),
              ),
              Positioned(
                left: Get.width*0.07,
                top: Get.height*0.5,
                child: GeneratedGroup105Widget(),
              ),
              Positioned(
                left: (Get.width*0.07) + 15,
                top: (Get.height*0.25) + 50,
                width: 99.0,
                height: 2.0,
                child: GeneratedTotalTokensWidget(),
              ),
              Positioned(
                left: (Get.width*0.07) + 15,
                top: (Get.height*0.25) + 75,
                width: 42.0,
                height: 5.0,
                child: Generated2098Widget(),
              ),
              Positioned(
                left: (Get.width*0.07) + 15,
                top: (Get.height*0.25) + 125,
                width: 35.0,
                height: 2.0,
                child: Generated$89Widget(),
              ),
              Positioned(
                left: (Get.width*0.07) + 15,
                top: (Get.height*0.25) + 100,
                right: null,
                bottom: null,
                width: 58.0,
                height: 2.0,
                child: GeneratedBalnceWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 42.0,
                width: 24.0,
                height: 24.0,
                child: GeneratedKeyboardbackspaceWidget2(),
              )
            ]),
      ),
    );
  }
}
