import 'package:flutter/material.dart';
import 'package:flutterapp/widgets/introScreen/start_screen_text.dart';

/* Rectangle Rectangle 19
    Autogenerated by FlutLab FTF Generator
  */
class RectangleWidget extends StatelessWidget {
  var _color;
  var _callbackfunction;
  RectangleWidget(this._color,this._callbackfunction);
  @override
  Widget build(BuildContext context) {
    return InkWell(
      
      splashColor: Color.fromARGB(255, 0, 68, 35),
      onTap: _callbackfunction,
      child: Container(
        width: MediaQuery.of(context).size.width * .70,
        height: MediaQuery.of(context).size.width * .50,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(102, 189, 189, 189),
              offset: Offset(-4.0, -4.0),
              blurRadius: 10.0,
            ),
            BoxShadow(
              color: Color.fromARGB(63, 0, 0, 0),
              offset: Offset(4.0, 4.0),
              blurRadius: 4.0,
            )
          ],
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 168, 168, 68),
              Color.fromARGB(255, 83, 102, 6)
            ],
          ),
        ),
        child: Align(alignment: Alignment.center, child: StartScreenText(this._color)),
      ),
    );
  }
}
