import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedintrowidget/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/newapp/generatedintrowidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/newapp/generatedintrowidget/generated/GeneratedGroup49Widget1.dart';
import 'package:flutterapp/newapp/generatedintrowidget/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/screens/intro_screen.dart';
import 'package:flutterapp/newapp/generatedintrowidget/generated/GeneratedGroup52Widget1.dart';
import 'package:get/get.dart';

/* Frame intro
    Autogenerated by FlutLab FTF Generator
  */
class Intro extends StatelessWidget {
  
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: Get.width,
        height: Get.height,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 236, 246, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: Get.width,
            height: Get.height,
            child: IntroScreen(),
          ),
          Positioned(
            left: 129.0,
            top: 513.0,
            right: null,
            bottom: null,
            width: 156.59182739257812,
            height: 166.40240478515625,
            child: GeneratedGroup1Widget1(),
          ),
          Positioned(
            left: 67.0,
            top: 402.0,
            right: null,
            bottom: null,
            width: 247.5,
            height: 53.0,
            child: GeneratedGroup49Widget1(),
          ),
          Positioned(
            left: Get.width * 0.21,
            top: Get.height * 0.4,
            right: null,
            bottom: null,
            width: Get.width * 0.7,
            height: Get.height * 0.3,
            child: GeneratedGroup48Widget1(),
          ),
          Positioned(
            left: -279.0,
            top: 550.0,
            right: null,
            bottom: null,
            width: 251.0,
            height: 54.38333511352539,
            child: GeneratedGroup50Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 776.0,
            right: null,
            bottom: null,
            width: 341.0,
            height: 58.0,
            child: GeneratedGroup52Widget1(),
          )
        ]),
      ),
    );
  }
}
