import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup80Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup107Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup113Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedVectorWidget71.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup87Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedScreenshot371Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup90Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup88Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/Generatedh5yztd9c55Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup89Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup82Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroupWidget55.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroupWidget31.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedThispuphasntuploadedavideoWidget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedJaronLukasWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup81Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedCheckbacksoonWidget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroupWidget1.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedGroup84Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedVectorWidget65.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedRectangle17686Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedLine41Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedLine40Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/newapp/generatedprofilewidget/generated/GeneratedRectangle17687Widget.dart';
import 'package:get/get.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class ProfileScreen extends StatelessWidget {
  static const String routeName = '/ProfileScreen';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: Get.width,
        height: Get.height,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 243, 230, 211),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            width: Get.width,
            height: Get.height * 0.29,
            child: GeneratedRectangle17686Widget(),
          ),
          //bottombar
          // Positioned(
          //   left: 0.0,
          //   top: 739.0,
          //   right: null,
          //   bottom: null,
          //   width: 390.0,
          //   height: 105.0,
          //   child: GeneratedRectangle17687Widget(),
          // ),
          //
          //edit profile widget
          Positioned(
            left: Get.width * 0.48,
            top: (Get.height * 0.12) + 50,
            child: GeneratedGroup84Widget(),
          ),
          //Name
          Positioned(
            left: Get.width * 0.48,
            top: Get.height * 0.12,
            child: GeneratedJaronLukasWidget(),
          ),
          //username
          Positioned(
            left: Get.width * 0.48,
            top: (Get.height * 0.12) + 25,
            child: Generatedh5yztd9c55Widget(),
          ),
          //woofs number
          Positioned(
            left: Get.width * 0.1,
            top: Get.height * 0.23,
            child: GeneratedGroup80Widget(),
          ),
          //friends number
          Positioned(
            left: Get.width * 0.42,
            top: Get.height * 0.23,
            child: GeneratedGroup81Widget(),
          ),
          //followings number
          Positioned(
            right: Get.width * 0.1,
            top: Get.height * 0.23,
            child: GeneratedGroup82Widget(),
          ),
          //line
          Positioned(
            left: Get.width * 0.09,
            top: Get.height * 0.36,
            width: Get.width * 0.7,
            height: 1.0,
            child: GeneratedLine15Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.040860608907846305;

              final double height = constraints.maxHeight * 0.00971937744538366;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.24600016276041667,
                    y: constraints.maxHeight * 0.9459978438101674,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedGroupWidget1(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.1724076686761318;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 67.2389907836914;

              double percentHeight = 0.07966705069157749;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 67.2389907836914;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.023076923076923078,
                    translateY: constraints.maxHeight * 0.8116113744075829,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget12())
              ]);
            }),
          ),
          //Bottom Home Item
          // Positioned(
          //   left: 23.0,
          //   top: 757.0,
          //   right: null,
          //   bottom: null,
          //   width: 38.0,
          //   height: 40.0,
          //   child: GeneratedGroup87Widget(),
          // ),
          //Bottom Discover Item
          // Positioned(
          //   left: 86.0,
          //   top: 759.562255859375,
          //   right: null,
          //   bottom: null,
          //   width: 52.0,
          //   height: 37.43768310546875,
          //   child: GeneratedGroup88Widget(),
          // ),
          //Bottom Update Item
          // Positioned(
          //   left: 255.0,
          //   top: 755.0,
          //   right: null,
          //   bottom: null,
          //   width: 46.0,
          //   height: 42.0,
          //   child: GeneratedGroup89Widget(),
          // ),
          //Bottom Profile Item
          // Positioned(
          //   left: 327.0,
          //   top: 757.0,
          //   right: null,
          //   bottom: null,
          //   width: 39.0,
          //   height: 40.0,
          //   child: GeneratedGroup90Widget(),
          // ),
          //Dog
          Positioned(
            left: Get.width * 0.01,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.47692307692307695;

              final double height = constraints.maxHeight * 0.10130788251687001;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.26153846153846155,
                    y: constraints.maxHeight * 0.5133554539974267,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedGroupWidget31(),
                    ))
              ]);
            }),
          ),
          //Text
          Positioned(
            top: Get.height * 0.62,
            child: GeneratedCheckbacksoonWidget(),
          ),
          //Text
          Positioned(
            top: (Get.height * 0.62) + 40,
            child: TransformHelper.translate(
                x: -1.50,
                y: 0.00,
                z: 0,
                child: GeneratedThispuphasntuploadedavideoWidget()),
          ),
          //Bottom Camera Item
          // Positioned(
          //   left: 168.0,
          //   top: 754.0,
          //   right: null,
          //   bottom: null,
          //   width: 54.0,
          //   height: 54.0,
          //   child: GeneratedGroup107Widget(),
          // ),
          //profile image
          Positioned(
            left: (Get.width * 0.15),
            top: Get.height * 0.117,
            child: GeneratedGroup113Widget(),
          ),
          //screenshot
          Positioned(
            left: Get.width * 0.1,
            top: Get.height * 0.03,
            child: GeneratedScreenshot371Widget(),
          ),
          Positioned(
            left: Get.width * 0.1 + 80,
            top: Get.height * 0.24,
            child: GeneratedLine40Widget(),
          ),
          Positioned(
            right: Get.width * 0.1 + 80,
            top: Get.height * 0.24,
            child: GeneratedLine41Widget(),
          ),
          Positioned(
            left: 0.0,
            top: Get.height*0.05,
            right: 0.0,
            bottom: 0.0,
            child: LayoutBuilder(builder:
                (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.05025641123453776;
              double scaleX = (constraints.maxWidth * percentWidth) /
                  19.600000381469727;

              double percentHeight = 0.023222749267144224;
              double scaleY = (constraints.maxHeight * percentHeight) /
                  19.600000381469727;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.1282051282051282,
                    translateY: constraints.maxHeight * 0.32109004739336494,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget65())
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: Get.height * 0.05,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.0641025641025641;

              final double height = constraints.maxHeight * 0.02962085308056872;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.4666666666666667,
                    y: constraints.maxHeight * 0.32109004739336494,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedGroupWidget55(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: Get.height * 0.05,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.05128205128205128;
              double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

              double percentHeight = 0.02843601895734597;
              double scaleY = (constraints.maxHeight * percentHeight) / 24.0;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.8205128205128205,
                    translateY: constraints.maxHeight * 0.32109004739336494,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget71())
              ]);
            }),
          ),
          Positioned(
            right: 10,
            top: Get.height * 0.03,
            child: GeneratedFrame2Widget(),
          )
        ]),
      ),
    );
  }
}
