import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedadwidget1/generated/GeneratedGroup93Widget1.dart';
import 'package:flutterapp/newapp/generatedadwidget1/generated/GeneratedGroupWidget267.dart';
import 'package:flutterapp/newapp/generatedadwidget1/generated/GeneratedClosecircleWidget1.dart';
import 'package:flutterapp/newapp/generatedadwidget1/generated/GeneratedImage4Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:get/get.dart';

/* Frame Ad
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body:Container(
        width: Get.width,
        height: Get.height,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.040860608907846305;

                  final double height =
                      constraints.maxHeight * 0.00971937744538366;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24600016276041667,
                        y: constraints.maxHeight * 0.9459978438101674,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget267(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedImage4Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1282051282051282;

                  final double height =
                      constraints.maxHeight * 0.05924170616113744;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8256410256410256,
                        y: constraints.maxHeight * 0.06635071090047394,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedClosecircleWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9384615384615385;

                  final double height =
                      constraints.maxHeight * 0.4324644549763033;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03076923076923077,
                        y: constraints.maxHeight * 0.35071090047393366,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup93Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
