import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedLine22Widget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedLine23Widget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedAddMusicWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedGroup100Widget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedGIFWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedRectangle17686Widget3.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedGroup83Widget1.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedKeyboardbackspaceWidget3.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedLine20Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedGroupWidget157.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedWriteaCaptionWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedActivityWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedLine21Widget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedAddLocationWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedTagPeopleWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedEditImageWidget.dart';
import 'package:flutterapp/newapp/generatedpostwidget/generated/GeneratedImage5Widget.dart';
import 'package:get/get.dart';

/* Frame post
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPostWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
      width: Get.width,
      height: Get.height,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          // overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 243, 230, 211),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: Get.width,
              height: Get.height*0.4,
              child: GeneratedRectangle17686Widget3(),
            ),
            Positioned(
              left: 39.0,
              top: 99.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 50.0,
              child: GeneratedGroup83Widget1(),
            ),
            Positioned(
              left: 100.0,
              top: 119.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 22.0,
              child: GeneratedWriteaCaptionWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 391.0,
              right: null,
              bottom: null,
              width: 86.0,
              height: 22.0,
              child: GeneratedAddLocationWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 431.0,
              right: null,
              bottom: null,
              width: 73.0,
              height: 22.0,
              child: GeneratedTagPeopleWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 471.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 22.0,
              child: GeneratedEditImageWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 511.0,
              right: null,
              bottom: null,
              width: 68.0,
              height: 22.0,
              child: GeneratedAddMusicWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 551.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 25.0,
              child: GeneratedActivityWidget(),
            ),
            Positioned(
              left: 48.0,
              top: 591.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedGIFWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width =
                    constraints.maxWidth * 0.040860608907846305;

                final double height =
                    constraints.maxHeight * 0.00971937744538366;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.24600016276041667,
                      y: constraints.maxHeight * 0.9459978438101674,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroupWidget157(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 27.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedKeyboardbackspaceWidget3(),
            ),
            Positioned(
              left: 124.0,
              top: 161.0,
              child: GeneratedImage5Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 422.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 1.0,
              child: GeneratedLine18Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 462.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 1.0,
              child: GeneratedLine19Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 502.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 1.0,
              child: GeneratedLine20Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 542.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 1.0,
              child: GeneratedLine21Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 582.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 1.0,
              child: GeneratedLine22Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 622.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 1.0,
              child: GeneratedLine23Widget(),
            ),
            Positioned(
              top: Get.height*0.8,
              child: GeneratedGroup100Widget(),
            )
          ]),
    ));
  }
}
