import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedCloseWidget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedFacebookWidget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedSigninwithGoogleWidget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedTermsofUsesWidget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedJoinourexclusivedogcommunityEnjoydogvideosgrowyourdogss.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedBycontinuingyouagreetoyumwoofsocialstermsofuseandconfir.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedSIGNUPFORFREEWidget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedPrivacyPolicyWidget.dart';
import 'package:flutterapp/newapp/generatedloginwidget/generated/GeneratedScreenshot361Widget.dart';
import 'package:get/get.dart';

/* Frame Login 
    Autogenerated by FlutLab FTF Generator
  */
class LoginScreen extends StatelessWidget {
   static const String routeName = '/LoginScreen';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
        width: Get.width,
        height: Get.height,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 230, 211),
                ),
              ),
              //Sign In with Google
              Positioned(
                left: Get.width*0.15,
                top: Get.height*0.5,
                right: null,
                bottom: null,
                width: Get.width*0.7,
                height: Get.height*0.052,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: Get.width*0.3,
                top: Get.height*0.515,
                right: null,
                bottom: null,
                width: Get.width*0.7,
                height: 24.0,
                child: GeneratedSigninwithGoogleWidget(),
              ),
              Positioned(
                left: Get.width*0.18,
                top: Get.height*0.512,
                right: null,
                bottom: null,
                width: 25.74955940246582,
                height: 25.74955940246582,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: Get.width*0.15,
                top: Get.height*0.56,
                right: null,
                bottom: null,
                width: Get.width*0.8,
                height: Get.height*0.052,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: Get.width*0.15,
                top: Get.height*0.62,
                right: null,
                bottom: null,
                width: Get.width*0.8,
                height: Get.height*0.052,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: Get.height*0.7,
                width: Get.width,
                height: 32.0,
                child:
                    GeneratedBycontinuingyouagreetoyumwoofsocialstermsofuseandconfir(),
              ),
              //done
              Positioned(
                left: Get.width*0.1,
                top: Get.height*0.8,
                width: 72.0,
                height: 14.0,
                child: GeneratedTermsofUsesWidget(),
              ),
              Positioned(
                right: Get.width*0.1,
                top: Get.height*0.8,
                width: 71.0,
                height: 14.0,
                child: GeneratedPrivacyPolicyWidget(),
              ),
              Positioned(
                top: Get.height*0.4,
                width: Get.width,
                height: 78.0,
                child:
                    GeneratedJoinourexclusivedogcommunityEnjoydogvideosgrowyourdogss(),
              ),
              Positioned(
                left: Get.width*0.22,
                top: Get.height*0.35,
                width: Get.width,
                height: 36.0,
                child: GeneratedSIGNUPFORFREEWidget(),
              ),
              Positioned(
                left: Get.width*0.18,
                top: Get.height*0.57,
                right: null,
                bottom: null,
                width: 28.0,
                height: 27.0,
                child: GeneratedFacebookWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloseWidget(),
              ),
              Positioned(
                left: Get.width*0.15,
                top: Get.height*0.1,
                width: Get.width*0.7,
                height: Get.height*0.22,
                child: GeneratedScreenshot361Widget(),
              )
            ]),
      ),
    );
  }
}
