import 'package:flutter/material.dart';

/* Frame Flash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedCam2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 390.0,
          height: 844.0,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
        ),
      ),
    ));
  }
}
