import 'package:flutter/material.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup118Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17692Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17687Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup89Widget2.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup90Widget2.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup114Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup116Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup115Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedEllipse320Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedEllipse321Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17699Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17695Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedVectorWidget115.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup108Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17696Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17697Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup88Widget2.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup111Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup87Widget2.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup117Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup110Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup109Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroup107Widget2.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17698Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17686Widget1.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedRectangle17694Widget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedTRENDINGPUPSWidget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedWoofhereWidget.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedGroupWidget97.dart';
import 'package:flutterapp/newapp/generateddiscoverwidget2/generated/GeneratedMagnifyWidget.dart';

/* Frame Discover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscoverWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 230, 211),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 261.0,
                child: GeneratedRectangle17697Widget(),
              ),
              Positioned(
                left: 195.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 261.0,
                child: GeneratedRectangle17698Widget(),
              ),
              Positioned(
                left: 370.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 261.0,
                child: GeneratedRectangle17699Widget(),
              ),
              //Trending pups background rectangle
              Positioned(
                left: 1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 137.0,
                child: GeneratedRectangle17692Widget(),
              ),
              // full top background
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 162.0,
                child: GeneratedRectangle17686Widget1(),
              ),
              
              
              
              
              Positioned(
                left: 13.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 41.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 67.09091186523438,
                height: 27.0,
                child: GeneratedGroup114Widget(),
              ),
              Positioned(
                left: 96.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 27.0,
                child: GeneratedGroup108Widget(),
              ),
              Positioned(
                left: 188.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 27.0,
                child: GeneratedGroup109Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 27.0,
                child: GeneratedGroup110Widget(),
              ),
              Positioned(
                left: 352.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 27.0,
                child: GeneratedGroup111Widget(),
              ),
              //searchbar
              Positioned(
                left: 112.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 40.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 331.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 340.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMagnifyWidget(),
              ),//////////////
              Positioned(
                left: 124.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 22.0,
                child: GeneratedWoofhereWidget(),
              ),
              
              Positioned(
                left: 20.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 14.0,
                child: GeneratedTRENDINGPUPSWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 25.0,
                child: GeneratedGroup115Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 25.0,
                child: GeneratedGroup118Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 74.0,
                child: GeneratedGroup116Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 74.0,
                child: GeneratedGroup117Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 261.0,
                child: GeneratedRectangle17694Widget(),
              ),
              Positioned(
                left: 195.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 261.0,
                child: GeneratedRectangle17695Widget(),
              ),
              Positioned(
                left: 370.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 261.0,
                child: GeneratedRectangle17696Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedEllipse320Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedEllipse321Widget(),
              )
            ]),
      ),
    ));
  }
}
